name: Deploy To Cloudflare

on:
  push:
    branches:
      - main
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install cheerio
        run: npm install cheerio

      - name: Set Start Command
        run: echo '{"scripts": {"start": "node lib/api.js"}}' > package.json

      - name: Build Worker
        run: npm run build

      - name: Debug Wrangler Action
        run: |
          npx wrangler whoami
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Deploy Worker
        run: npx wrangler deploy dist/index.js
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
